"""initial

Revision ID: 484d73f7a77d
Revises:
Create Date: 2025-11-18 20:38:22.925035

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "484d73f7a77d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original", sa.String(length=2048), nullable=False),
        sa.Column("short", sa.String(length=16), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("url_map")
    # ### end Alembic commands ###
